### ISSUE TITLE
Differences from LnL7/nix-docker

### ISSUE THREAD

**Issue by colemickens** [garbas/nix-docker-nix#1]
Hi @garbas.

I noticed that you call out some other projects that this presumably takes inspiration from or builds on. Can you add a line or two about how this differs from them? In particular, what does this do that isn't done in https://github.com/LnL7/nix-docker, and why not add it there?

Thanks!

**Comment by nlewo** [comment]
I think the main difference is to not rely on Docker tools (`Dockerfile`, `docker build`) to build the Nix image.

**Comment by garbas** [comment]
@colemickens exactly what @nlewo said, i updated the readme i hope that clears some things.
